defmodule Transitmaps.Catalog.Countries do
  @moduledoc """
  English names for the countries the feed catalog covers. Codes outside
  this table fall back to the bare ISO code, so a country newly added to
  the catalog still shows up — just less politely named.
  """

  @names %{
    "AE" => "United Arab Emirates",
    "AL" => "Albania",
    "AR" => "Argentina",
    "AT" => "Austria",
    "AU" => "Australia",
    "BA" => "Bosnia & Herzegovina",
    "BE" => "Belgium",
    "BG" => "Bulgaria",
    "BM" => "Bermuda",
    "BO" => "Bolivia",
    "BR" => "Brazil",
    "BY" => "Belarus",
    "CA" => "Canada",
    "CD" => "Congo - Kinshasa",
    "CG" => "Congo - Brazzaville",
    "CH" => "Switzerland",
    "CI" => "Côte d’Ivoire",
    "CL" => "Chile",
    "CM" => "Cameroon",
    "CN" => "China",
    "CO" => "Colombia",
    "CR" => "Costa Rica",
    "CY" => "Cyprus",
    "CZ" => "Czechia",
    "DE" => "Germany",
    "DK" => "Denmark",
    "DO" => "Dominican Republic",
    "DZ" => "Algeria",
    "EE" => "Estonia",
    "EG" => "Egypt",
    "ES" => "Spain",
    "ET" => "Ethiopia",
    "FI" => "Finland",
    "FR" => "France",
    "GB" => "United Kingdom",
    "GE" => "Georgia",
    "GG" => "Guernsey",
    "GH" => "Ghana",
    "GL" => "Greenland",
    "GR" => "Greece",
    "HN" => "Honduras",
    "HR" => "Croatia",
    "HU" => "Hungary",
    "ID" => "Indonesia",
    "IE" => "Ireland",
    "IL" => "Israel",
    "IN" => "India",
    "IS" => "Iceland",
    "IT" => "Italy",
    "JP" => "Japan",
    "KE" => "Kenya",
    "KH" => "Cambodia",
    "LK" => "Sri Lanka",
    "LT" => "Lithuania",
    "LU" => "Luxembourg",
    "LV" => "Latvia",
    "MA" => "Morocco",
    "MC" => "Monaco",
    "MD" => "Moldova",
    "ME" => "Montenegro",
    "MK" => "North Macedonia",
    "ML" => "Mali",
    "MX" => "Mexico",
    "MY" => "Malaysia",
    "NG" => "Nigeria",
    "NI" => "Nicaragua",
    "NL" => "Netherlands",
    "NO" => "Norway",
    "NZ" => "New Zealand",
    "OM" => "Oman",
    "PE" => "Peru",
    "PH" => "Philippines",
    "PL" => "Poland",
    "PT" => "Portugal",
    "RO" => "Romania",
    "RS" => "Serbia",
    "RU" => "Russia",
    "RW" => "Rwanda",
    "SA" => "Saudi Arabia",
    "SE" => "Sweden",
    "SG" => "Singapore",
    "SI" => "Slovenia",
    "SK" => "Slovakia",
    "SL" => "Sierra Leone",
    "TH" => "Thailand",
    "TN" => "Tunisia",
    "TR" => "Türkiye",
    "TW" => "Taiwan",
    "UA" => "Ukraine",
    "UG" => "Uganda",
    "US" => "United States",
    "UY" => "Uruguay",
    "XK" => "Kosovo",
    "ZA" => "South Africa",
    "ZW" => "Zimbabwe"
  }

  @doc "The English name for an ISO 3166-1 alpha-2 `code`."
  def name(code), do: Map.get(@names, code, code)
end
